[app]
name = "Salz"
menu = "Badge"

[entry]
class = "SalzApp"

[metadata]
author = "fuero <fuerob@gmail.com>, tth, nother, rnbwdsh"
license = "LGPL-3.0-only"
url = "https://github.com/TTH-Someone-stole-my-name/salzamt-badge"
