[app]
name = "Salzamt Nick App"
menu = "Badge"

[entry]
class = "SalzamtNickApp"

[metadata]
author = "fuero <fuerob@gmail.com>, tth, nother"
license = "LGPL-3.0-only"
url = "https://github.com/TTH-Someone-stole-my-name/salzamt-badge"
